<?php
/**
 * @file
 *
 */

use Drupal\block\Entity\Block;
use Drupal\block_content\Entity\BlockContent;

/**
 * Implements hook_cron().
 */
function block_updates_cron() {
  $query = \Drupal::entityQuery('block_content')
    ->condition('type', 'stock_exchange_rate_card');

  // get all block's ids of type stock_exchange_rate_card
  $blocks_ids = $query->execute();

  if (is_array($blocks_ids) && sizeof($blocks_ids) > 0) {
    foreach ($blocks_ids as $bid) {
      $block       = BlockContent::load($bid);
      $blockSymbol = $block->get('field_symbol')->getString();

      // makes httprequest using Guzzle, sending the current block symbol
      $data = [];
      $client = \Drupal::httpClient();
      try {
        $url = 'http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol=' . $blockSymbol . '&callback=myFunction';
        $response = $client->get($url, [
                                 'headers' => [
                                                'Accept' => 'text/plain'
                                             ]
                                 ]);
        $data = (string)$response->getBody();

        if (!empty($data)) {
          $data = json_decode($data, TRUE);
        }
      } catch (RequestException $e) {
        watchdog_exception('block_updates', $e->getMessage());
      }

      if (sizeof($data) > 0) {
        $lastPrice = (isset($data['LastPrice'])) ? $data['LastPrice'] : '';
        $change    = (isset($data['Change'])) ? $data['Change'] : '';

        $block->set('field_last_price', $lastPrice);
        $block->set('field_change', $change);
        $block->save();
      }
    }
  }

}
